DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS temphum;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  is_admin INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE temphum (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  measured TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  temperature INTEGER NOT NULL,
  humidity INTEGER NOT NULL
);